//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabeceraFactura()
        {
            this.DetalleFacturas = new HashSet<DetalleFactura>();
        }
    
        public System.Guid Id { get; set; }
        public string NombreCliente { get; set; }
        public string IdentificadorCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal SubTotalIva { get; set; }
        public decimal SubTotalNoIva { get; set; }
        public decimal SubTotalSuma { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public int Secuencial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }
    }
}
